OnlineCommercialAutomation/Controllers/StatisticController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OnlineCommercialAutomation.Models.Classes;

namespace OnlineCommercialAutomation.Controllers
{
    public class StatisticController : Controller
    {
        Context context = new Context();    
        public ActionResult Index()
        {

            ViewBag.d1 = context.Customers.Count();
            ViewBag.d2 = context.Products.Count();
            ViewBag.d3 = context.Personals.Count();
            ViewBag.d4 = context.Categories.Count();
            ViewBag.d5 = context.Products.Sum(i => i.Stock);
            ViewBag.d6 = context.Products.Select(i => i.Manufacturer).Distinct().Count();
            ViewBag.d7 = context.Products.Count(i => i.Stock < 10);

            //var maxPrice = context.Products.Max(i => i.SalePrice);
            //ViewBag.d8 = context.Products.Where(i => i.SalePrice == maxPrice).Select(p =>p.Name).FirstOrDefault().ToString();

           
            ViewBag.d8 = context.Products.OrderByDescending(i => i.SalePrice).Select(k=>k.Name).FirstOrDefault().ToString();


            //var minPrice = context.Products.Min(i => i.SalePrice);
            //ViewBag.d9 = context.Products.Where(i => i.SalePrice == minPrice).Select(p => p.Name).FirstOrDefault().ToString();

            ViewBag.d9 = context.Products.OrderBy(i => i.SalePrice).Select(k => k.Name).FirstOrDefault().ToString();

            ViewBag.d10 = context.Products.Where(i => i.Name == "Fridge").Sum(k => k.Stock).ToString();

            ViewBag.d11 = context.Products.Where(i => i.Name == "IPhone").Sum(k => k.Stock).ToString();

            ViewBag.d12 = context.Products.GroupBy(i => i.Manufacturer).OrderByDescending(k=>k.Count()).Select(y => y.Key).FirstOrDefault();

            var mostSaledProductId = context.SalesTransactionS.GroupBy(i => i.ProductId).OrderByDescending(k => k.Sum(p => p.Amount)).Select(y => y.Key).FirstOrDefault();
            ViewBag.d13 = context.Products.Where(i=>i.Id == mostSaledProductId).Select(k=>k.Name).FirstOrDefault();

            ViewBag.d14 = context.SalesTransactionS.Sum(x=>x.TotalPrice);

            ViewBag.d15 = context.SalesTransactionS.Count(x => x.Date == DateTime.Today);


            ViewBag.d16 = context.SalesTransactionS.Where(x => x.Date == DateTime.Today).Select(i => (decimal?)i.TotalPrice)
                     .Sum() ?? 0;



            return View();
        }


        public ActionResult SimpleTables()
        {

            var query = from x in context.Customers
                        group x by x.City into g
                        select new SimpleTableGroup
                        {
                            City = g.Key,
                            Total = g.Count()
                        };

            return View(query.ToList());
        }

        public PartialViewResult FirstPartial()
        {

            var personalCount = from x in context.Personals
                                group x by x.Department.Name into g
                                select new PersonalGroup
                                {
                                    Department = g.Key,
                                    Amount = g.Count()
                                };
            return PartialView(personalCount.ToList());
        }


        public PartialViewResult SecondPartial()
        {

            var customers = context.Customers.ToList();
            return PartialView(customers);
        }

        public PartialViewResult ThirdPartial()
        {

            var products = context.Products.ToList();
            return PartialView(products);
        }


        public PartialViewResult FourthPartial()
        {
            var manufacturerQuery = from x in context.Products
                                group x by x.Manufacturer into g
                                select new ManufacturerGroup
                                {
                                    manufacturer = g.Key,
                                    count = g.Count()
                                };
            return PartialView(manufacturerQuery.ToList());
        }


        public PartialViewResult FifthPartial()
        {
            var categoryGroupQuery = from x in context.Products
                                    group x by x.Category.Name into g
                                    select new CategoryGroup
                                    {
                                        Category = g.Key,
                                        Count = g.Count()
                                    };
            return PartialView(categoryGroupQuery.ToList());
        }
    }


}

OnlineCommercialAutomation/Views/Statistic/FifthPartial.cshtml
@model List<OnlineCommercialAutomation.Models.Classes.CategoryGroup>

<div class="card">
    <div class="card-header">
        <h3 class="card-title">Category Table</h3>
    </div>
    <!-- /.card-header -->
    <div class="card-body">
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th style="width: 10px">#</th>
                    <th>Category</th>
                    <th>Progress</th>
                    <th style="width: 40px">Count</th>
                </tr>
            </thead>
            <tbody>
                @{
                    var totalAmount = Model.Sum(x => x.Count);
                    int i = 1;
                }
                @foreach (var item in Model)
                {
                    var percentage = (double)item.Count / totalAmount * 100;

                    string progressBarClass;
                    if (percentage <= 30)
                    {
                        progressBarClass = "bg-primary";
                    }
                    else if (percentage <= 60)
                    {
                        progressBarClass = "bg-warning";
                    }
                    else
                    {
                        progressBarClass = "bg-success";
                    }

                    string badgeClass;
                    if (percentage <= 30)
                    {
                        badgeClass = "badge bg-danger";
                    }
                    else if (percentage <= 60)
                    {
                        badgeClass = "badge bg-warning";
                    }
                    else
                    {
                        badgeClass = "badge bg-success";
                    }
                    <tr>
                        <td>@i.</td>
                        <td>@item.Category</td>
                        <td>
                            <div class="progress progress-xs">
                                <div class="progress-bar @progressBarClass" style="width: @percentage%"></div>
                            </div>
                        </td>
                        <td><span class="badge bg-@badgeClass">@item.Count</span></td>
                    </tr>
                    i++;
                }

            </tbody>
        </table>
    </div>
    <!-- /.card-body -->
    <div class="card-footer clearfix">
        <ul class="pagination pagination-sm m-0 float-right">
            <li class="page-item"><a class="page-link" href="#">&laquo;</a></li>
            <li class="page-item"><a class="page-link" href="#">1</a></li>
            <li class="page-item"><a class="page-link" href="#">2</a></li>
            <li class="page-item"><a class="page-link" href="#">3</a></li>
            <li class="page-item"><a class="page-link" href="#">&raquo;</a></li>
        </ul>
    </div>
</div>

OnlineCommercialAutomation/Views/Statistic/FirstPartial.cshtml
@model IEnumerable<OnlineCommercialAutomation.Models.Classes.PersonalGroup>


<div class="card">
    <div class="card-header">
        <h3 class="card-title">Department Personal Counts</h3>
    </div>
    <!-- /.card-header -->
    <div class="card-body p-0">
        <table class="table table-sm">
            <thead>
                <tr>
                    <th style="width: 10px">#</th>
                    <th>Department</th>
                    <th>Progress Bar</th>
                    <th style="width: 40px">Count</th>
                </tr>
            </thead>
            <tbody>
                @{
                    var totalAmount = Model.Sum(x => x.Amount);
                    int i = 1;
                }
                @foreach (var item in Model)
                {
                    var percentage = (double)item.Amount / totalAmount * 100;

                    string progressBarClass;
                    if (percentage <= 30)
                    {
                        progressBarClass = "bg-primary";
                    }
                    else if (percentage <= 60)
                    {
                        progressBarClass = "bg-warning";
                    }
                    else
                    {
                        progressBarClass = "bg-success";
                    }

                    string badgeClass;
                    if (percentage <= 30)
                    {
                        badgeClass = "badge bg-danger";
                    }
                    else if (percentage <= 60)
                    {
                        badgeClass = "badge bg-warning";
                    }
                    else
                    {
                        badgeClass = "badge bg-success";
                    }

                    
                    <tr>
                        <td>@i.</td>
                        <td>@item.Department</td>
                        <td>
                            <div class="progress progress-xs">
                                
                                <div class="progress-bar @progressBarClass" style="width: @percentage%"></div>
                            </div>
                        </td>
                        <td><span class="badge bg-@badgeClass">@item.Amount</span></td>
                    </tr>
                }


            </tbody>
        </table>
    </div>
    <!-- /.card-body -->
</div>

OnlineCommercialAutomation/Views/Statistic/FourthPartial.cshtml
@model List<OnlineCommercialAutomation.Models.Classes.ManufacturerGroup>

<div class="card">
    <div class="card-header">
        <h3 class="card-title">Product Manufacturer Table</h3>
    </div>
    <!-- /.card-header -->
    <div class="card-body p-0">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th style="width: 10px">#</th>
                    <th>Manufacturer</th>
                    <th>Progress</th>
                    <th style="width: 40px">Count</th>
                </tr>
            </thead>
            <tbody>
                @{
                    var totalAmount = Model.Sum(x => x.count);
                    int i = 1;
                }
                @foreach (var item in Model)
                {
                    var percentage = (double)item.count / totalAmount * 100;

                    string progressBarClass;
                    if (percentage <= 30)
                    {
                        progressBarClass = "bg-primary";
                    }
                    else if (percentage <= 60)
                    {
                        progressBarClass = "bg-warning";
                    }
                    else
                    {
                        progressBarClass = "bg-success";
                    }

                    string badgeClass;
                    if (percentage <= 30)
                    {
                        badgeClass = "badge bg-danger";
                    }
                    else if (percentage <= 60)
                    {
                        badgeClass = "badge bg-warning";
                    }
                    else
                    {
                        badgeClass = "badge bg-success";
                    }
                    <tr>
                        <td>@i.</td>
                        <td>@item.manufacturer</td>
                        <td>
                            <div class="progress progress-xs">
                                <div class="progress-bar @progressBarClass" style="width: @percentage%"></div>
                            </div>
                        </td>
                        <td><span class="badge bg-@badgeClass">@item.count</span></td>
                    </tr>
                    i++;
                }


            </tbody>
        </table>
    </div>
    <!-- /.card-body -->
</div>

OnlineCommercialAutomation/Views/Statistic/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}




<!--
Author: W3layouts
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE html>
<html>
<head>

    <!-- Custom Theme files -->
    <link href="~/web2/css/style.css" rel="stylesheet" type="text/css" media="all" />
    <!-- Custom Theme files -->
    <script src="~/web2/js/jquery.min.js"></script>
    <link rel="stylesheet" href="~/web2/css/font-awesome.css">
    <!-- Custom Theme files -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="keywords" content="Metro Panel Responsive web template, Bootstrap Web Templates, Flat Web Templates, Andriod Compatible web template,
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyErricsson, Motorola web design" />
    <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
    <!--webfont-->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

    <script src="~/web2/js/zingchart.min.js"></script>
    <script src="~/web2/js/zingchart.jquery.js"></script>
    <script src="~/web2/js/jquery.easydropdown.js"></script>
    <script src="~/web2/js/jquery.nicescroll.js"></script>

    <link href="~/web2/css/jqvmap.css" media="screen" rel="stylesheet" type="text/css" />


    <script src="~/web2/js/easyResponsiveTabs.js" type="text/javascript"></script>

    <link href="~/web2/css/nav.css" rel="stylesheet" type="text/css" media="all" />
    <script src="~/web2/js/main.js"></script> <!-- Resource jQuery -->
    <!-- chart -->
    <script src="~/web2/js/Chart1.js"></script>
    <!-- //chart -->
</head>
<body>
    <div class="total-content">
        <div class="list_of_members">
            <div class="sales" style="background-color:#1abc9c">
                <div class="icon-text">
                    <h3>@ViewBag.d1</h3>
                    <p>Total Customer Count</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="new-users" style="background-color:#2ecc71">

                <div class="icon-text">
                    <h3>@ViewBag.d2</h3>
                    <p>Ürün Sayısı</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="orders" style="background-color:#3498db">

                <div class="icon-text">
                    <h3>@ViewBag.d3</h3>
                    <p>Personel Sayısı</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="visitors" style="background-color:#9b59b6">

                <div class="icon-text">
                    <h3>@ViewBag.d4</h3>
                    <p>Kategori Sayısı</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
    <div class="clearfix"></div>

    <div class="total-content">
        <div class="list_of_members">
            <div class="sales" style="background-color:#16a085">
                <div class="icon-text">
                    <h3>@ViewBag.d5</h3>
                    <p>Toplam Stok</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="new-users" style="background-color:#27ae60">

                <div class="icon-text">
                    <h3>@ViewBag.d6</h3>
                    <p>Marka Sayısı</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="orders" style="background-color:#2980b9">

                <div class="icon-text">
                    <h3>@ViewBag.d7</h3>
                    <p>Kritik Seviye</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="visitors" style="background-color:#8e44ad">

                <div class="icon-text">
                    <h3>@ViewBag.d8</h3>
                    <p>Max Fiyatlı Ürün</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>


    <div class="clearfix"></div>

    <div class="total-content">
        <div class="list_of_members">
            <div class="sales" style="background-color:#f1c40f">
                <div class="icon-text">
                    <h3>@ViewBag.d9</h3>
                    <p>Min Fiyatlı Ürün</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="new-users" style="background-color:#e67e22">

                <div class="icon-text">
                    <h3>@ViewBag.d12</h3>
                    <p>Max Marka</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="orders" style="background-color:#e74c3c">

                <div class="icon-text">
                    <h3>@ViewBag.d10</h3>
                    <p>Buzdolabı Sayısı</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="visitors" style="background-color:#95a5a6">

                <div class="icon-text">
                    <h3>@ViewBag.d11</h3>
                    <p>Laptop Sayısı</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>

    <div class="clearfix"></div>

    <div class="total-content">
        <div class="list_of_members">
            <div class="sales" style="background-color:#f39c12">
                <div class="icon-text">
                    <h3>@ViewBag.d13</h3>
                    <p>En Çok Satan</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="new-users" style="background-color:#d35400">

                <div class="icon-text">
                    <h3>@ViewBag.d14</h3>
                    <p>Kasadaki Tutar</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="orders" style="background-color:#c0392b">

                <div class="icon-text">
                    <h3>@ViewBag.d15</h3>
                    <p>Bugünkü Satşlar</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="visitors" style="background-color:#7f8c8d">

                <div class="icon-text">
                    <h3>@ViewBag.d16</h3>
                    <p>Bugünkü Kasa</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
</body>
</html>
</html>

OnlineCommercialAutomation/Views/Statistic/SecondPartial.cshtml
@model List<OnlineCommercialAutomation.Models.Classes.Customer>

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Customer Hover Table</h3>

                <div class="card-tools">
                    <div class="input-group input-group-sm" style="width: 150px;">
                        <input type="text" name="table_search" class="form-control float-right" placeholder="Search">

                        <div class="input-group-append">
                            <button type="submit" class="btn btn-default"><i class="fas fa-search"></i></button>
                        </div>
                    </div>
                </div>
            </div>
            <!-- /.card-header -->
            <div class="card-body table-responsive p-0">
                <table class="table table-hover text-nowrap">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Customer Name</th>
                            <th>City</th>
                            <th>Mail</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>@item.Id</td>
                                <td>@item.Name @item.Surname</td>
                                <td>@item.City</td>
                                <td>@item.Mail</td>
                                
                            </tr>
                        }


                    </tbody>
                </table>
            </div>
            <!-- /.card-body -->
        </div>
        <!-- /.card -->
    </div>
</div>

OnlineCommercialAutomation/Views/Statistic/SimpleTables.cshtml
@model IEnumerable<OnlineCommercialAutomation.Models.Classes.SimpleTableGroup>
@{
    ViewBag.Title = "SimpleTables";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br />
<h2>Simple Tables</h2>

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>AdminLTE 3 | Simple Tables</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/AdminLTE-3.0.4//plugins/fontawesome-free/css/all.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/AdminLTE-3.0.4/dist/css/adminlte.min.css">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>
<body class="hold-transition sidebar-mini">
    <div class="wrapper">
        <!-- Navbar -->
       
        <!-- Content Wrapper. Contains page content -->
        
          

            <!-- Main content -->
            <section class="content">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-md-6">
                            @Html.Action("FifthPartial", "Statistic")
                            <!-- /.card -->
                            <br />
                            @Html.Action("FirstPartial", "Statistic")

                            <!-- /.card -->
                        </div>
                        <!-- /.col -->
                        <div class="col-md-6">
                            <div class="card">
                                <div class="card-header">
                                    <h3 class="card-title">Customer City Table</h3>

                                    <div class="card-tools">

                                    </div>
                                </div>
                                <!-- /.card-header -->
                                <div class="card-body p-0">
                                    <table class="table">
                                        <thead>
                                            <tr>
                                                <th style="width: 10px">#</th>
                                                <th>City</th>
                                                <th>Progress Bar</th>
                                                <th style="width: 40px">Amount</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @{
                                                var totalAmount = Model.Sum(x => x.Total);
                                                int i = 1;
                                            }
                                            @foreach (var item in Model)
                                            {

                                                var percentage = (double)item.Total / totalAmount * 100;

                                                string progressBarClass;
                                                if (percentage <= 30)
                                                {
                                                    progressBarClass = "bg-primary";
                                                }
                                                else if (percentage <= 60)
                                                {
                                                    progressBarClass = "bg-warning";
                                                }
                                                else
                                                {
                                                    progressBarClass = "bg-success";
                                                }


                                                string badgeClass;
                                                if (percentage <= 30)
                                                {
                                                    badgeClass = "badge bg-danger";
                                                }
                                                else if (percentage <= 60)
                                                {
                                                    badgeClass = "badge bg-warning";
                                                }
                                                else
                                                {
                                                    badgeClass = "badge bg-success";
                                                }
                                                <tr>
                                                    <td>@i.</td>
                                                    <td>@item.City</td>
                                                    <td>
                                                        <div class="progress progress-xs">
                                                            <div class="progress-bar @progressBarClass" style="width: @percentage%"></div>
                                                        </div>
                                                    </td>
                                                    <td><span class="badge bg-@badgeClass">@percentage%</span></td>
                                                </tr>
                                                i++;

                                            }

                                        </tbody>
                                    </table>
                                </div>
                                <!-- /.card-body -->
                            </div>
                            <!-- /.card -->

                            @Html.Action("FourthPartial", "Statistic")
                            <!-- /.card -->
                        </div>
                        <!-- /.col -->
                    </div>
                    <!-- /.row -->
                    @Html.Action("SecondPartial", "Statistic")
                    <!-- /.row -->
                    @Html.Action("ThirdPartial", "Statistic")

                    <!-- /.row -->
                </div><!-- /.container-fluid -->
            </section>
            <!-- /.content -->
        
       

        <!-- Control Sidebar -->
        <aside class="control-sidebar control-sidebar-dark">
            <!-- Control sidebar content goes here -->
        </aside>
        <!-- /.control-sidebar -->
    </div>
    <!-- ./wrapper -->
    <!-- jQuery -->
    <script src="~/AdminLTE-3.0.4/plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap 4 -->
    <script src="~/AdminLTE-3.0.4/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- AdminLTE App -->
    <script src="~/AdminLTE-3.0.4/dist/js/adminlte.min.js"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="~/AdminLTE-3.0.4/dist/js/demo.js"></script>
</body>
</html>

OnlineCommercialAutomation/Views/Statistic/ThirdPartial.cshtml
@using OnlineCommercialAutomation.Models.Classes
@model List<Product>
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Product Info Table</h3>

                <div class="card-tools">
                    <div class="input-group input-group-sm" style="width: 150px;">
                        <input type="text" name="table_search" class="form-control float-right" placeholder="Search">

                        <div class="input-group-append">
                            <button type="submit" class="btn btn-default"><i class="fas fa-search"></i></button>
                        </div>
                    </div>
                </div>
            </div>
            <!-- /.card-header -->
            <div class="card-body table-responsive p-0" style="height: 300px;">
                <table class="table table-head-fixed text-nowrap">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Product Name</th>
                            <th>Manufacturer</th>
                            <th>Stock</th>
                            <th>Purchease Price</th>
                            <th>Sale Price</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>@item.Id</td>
                                <td>@item.Name</td>
                                <td>@item.Manufacturer</td>
                                <td>@item.Stock</td>
                                <td>@item.PurchasePrice $</td>
                                <td>@item.SalePrice $</td>
                                
                            </tr>
                        }


                    </tbody>
                </table>
            </div>
            <!-- /.card-body -->
        </div>
        <!-- /.card -->
    </div>
</div>